module.exports.files = {
    webcore: [
        '/client/js/Core/namespace.js',
        '/client/js/Ui/namespace.js',
        '/client/js/Utils/sc_keynodes.js',
        '/client/js/Utils/utils.js',
        '/client/js/Utils/sc_helper.js',
        '/client/js/Utils/stringview.js',
        '/client/js/Utils/cache.js',
        '/client/js/Utils/sctp.js',
        '/client/js/Utils/fqueue.js',
        '/client/js/Utils/binary.js',
        '/client/js/Utils/triples.js',
        '/client/js/Utils/logUtils.js',
        '/client/js/Core/debug.js',
        '/client/js/Core/server.js',
        '/client/js/Core/main.js',
        '/client/js/Core/arguments.js',
        '/client/js/Core/componentsandbox.js',
        '/client/js/Core/translation.js',
        '/client/js/Core/componentmanger.js',
        '/client/js/Core/eventmanager.js',
        '/client/js/Ui/core.js',
        '/client/js/Ui/menu.js',
        '/client/js/Ui/ContextSwitcher.js',
        '/client/js/Ui/eekbPanel.js',
        '/client/js/Ui/langpanel.js',
        '/client/js/Ui/locker.js',
        '/client/js/Ui/searchpanel.js',
        '/client/js/Ui/KeyboardHandler.js',
        '/client/js/Ui/taskpanel.js',
        '/client/js/Ui/argumentspanel.js',
        '/client/js/Ui/windowmanager.js',
        '/client/js/Ui/OpenComponentHandler.js',
        '/client/js/Ui/userpanel.js'
    ],
    scg: [
        "components/scg/src/gwf-file-creater.js",
        "components/scg/src/gwf-file-loader.js",
        "components/scg/src/gwf-model-objects.js",
        "components/scg/src/gwf-object-info-reader.js",
        "components/scg/src/scg-object-builder.js",
        "components/scg/src/scg.js",
        "components/scg/src/scg-debug.js",
        "components/scg/src/scg-math.js",
        "components/scg/src/scg-model-objects.js",
        "components/scg/src/scg-alphabet.js",
        "components/scg/src/scg-render.js",
        "components/scg/src/scg-scene.js",
        "components/scg/src/scg-layout.js",
        "components/scg/src/scg-tree.js",
        "components/scg/src/scg-struct.js",
        "components/scg/src/scg-object-creator.js",
        "components/scg/src/scg-component.js",
        "components/scg/src/listener/scg-mode-bus.js",
        "components/scg/src/listener/scg-mode-contour.js",
        "components/scg/src/listener/scg-mode-edge.js",
        "components/scg/src/listener/scg-mode-link.js",
        "components/scg/src/listener/scg-mode-select.js",
        "components/scg/src/command/append-object.js",
        "components/scg/src/command/command-manager.js",
        "components/scg/src/command/create-node.js",
        "components/scg/src/command/create-edge.js",
        "components/scg/src/command/create-bus.js",
        "components/scg/src/command/create-contour.js",
        "components/scg/src/command/create-link.js",
        "components/scg/src/command/change-idtf.js",
        "components/scg/src/command/change-content.js",
        "components/scg/src/command/change-type.js",
        "components/scg/src/command/delete-objects.js",
        "components/scg/src/command/move-object.js",
        "components/scg/src/command/move-line-point.js",
        "components/scg/src/command/get-node-from-memory.js",
        "components/scg/src/command/wrapper-command.js"
    ],
    scs: [
        "components/scs/src/scs.js",
        "components/scs/src/scs-viewer.js",
        "components/scs/src/scs-output.js",
        "components/scs/src/scs-types.js",
        "components/scs/src/scn-output.js",
        "components/scs/src/scn-tree.js",
        "components/scs/src/scn-highlighter.js",
        "components/scs/src/scs-component.js"
    ]
};
module.exports.dev = {
    js: [...module.exports.files.webcore,
        "/static/components/js/scs/scs.js",
        "/static/components/js/scg/scg.js",
        "/static/components/js/image/image.js",
        "/static/components/js/txt/txt.js",
        "/static/components/js/html/html.js",
        "/static/components/js/youtube/youtubelink.js",
        "/static/components/js/map/googlemaplink.js",
        "/static/components/js/github/github.js",
        "/static/components/js/pdf/pdf.js",
        "/static/components/js/file-saver/FileSaver.min.js",
        "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-treeview/1.2.0/bootstrap-treeview.min.js"
    ],
    css: [
        "/static/components/css/scg.css",
        "/static/components/css/scs.css",
        "/static/components/css/html.css",
        "/static/components/css/github.css",
        "/client/css/core.css",
        "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-treeview/1.2.0/bootstrap-treeview.min.css", "/static/components/css/github.css"
    ]
};
module.exports.current = {
    js: [
        "/static/components/js/sc-web-core.js",
        "/static/components/js/scs/scs.js",
        "/static/components/js/scg/scg.js",
        "/static/components/js/image/image.js",
        "/static/components/js/txt/txt.js",
        "/static/components/js/html/html.js",
        "/static/components/js/youtube/youtubelink.js",
        "/static/components/js/map/googlemaplink.js",
        "/static/components/js/github/github.js",
        "/static/components/js/pdf/pdf.js",
        "/static/components/js/file-saver/FileSaver.min.js",
    ],
    css: [
        "/static/components/css/scg.css",
        "/static/components/css/scs.css",
        "/static/components/css/html.css",
        "/static/components/css/github.css",
    ]
};
module.exports.single = {
    scg: {
        js: [
            "../../client/static/common/jquery/jquery-2.1.3.js",
            "../../client/static/common/jquery/jquery.namespace.js",
            "../../client/static/common/bootstrap/js/bootstrap.min.js",
            "../../client/static/common/typeahead/typeahead.bundle.min.js",
            "../../client/static/common/context/context.js",
            "../../client/static/common/kinetic/kinetic-v4.0.1.js",
            "../../client/static/common/d3/d3.js",
            "../../client/static/common/highlight/highlight.min.js",
            "../../client/static/common/base64/base64.min.js",
            "../../client/static/common/pdf/pdf.js",
            "../../client/static/common/pdf/pdf.worker.js",
            "../../client/js/Utils/sctp.js",
            "../../client/static/components/js/file-saver/FileSaver.min.js",
            "http://0.0.0.0:8080/skewer",
            "src/single-application/init.js",
            ...module.exports.files.scg.map(path => `/${path}`)
        ],
        css: [
            "src/single-application/index.css",
            "../../client/static/common/bootstrap/css/bootstrap.min.css",
            "../../client/static/common/bootstrap/css/bootstrap-multilevel.css",
            "../../client/static/common/highlight/googlecode.css",
            "../../client/static/common/context/context.standalone.css",
            "static/components/css/scg.css"
        ]
    }
};